In [11]:
import pandas as pd

In [12]:
pd.__version__

'3.0.3'

In [13]:
data = {
    "name":["ahmed","john","faduma"],
    "age":[33,54,18],
}
dataset = pd.DataFrame(data)
dataset

     name  age
0   ahmed   33
1    john   54
2  faduma   18

In [14]:
print(dataset.shape)
print(dataset['age'].mean())
print(dataset['age'].max())
print(dataset['age'].std())

(3, 2)
35.0
54
18.083141320025124

In [15]:
dataset.describe()

             age
count   3.000000
mean   35.000000
std    18.083141
min    18.000000
25%    25.500000
50%    33.000000
75%    43.500000
max    54.000000

In [ ]:
dataset[dataset['age'] > 20] # conditional select

    name  age
0  ahmed   33
1   john   54